[colors.bright]
black = "0x4b5263"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xbe5046"
white = "0x3e4452"
yellow = "0xd19a66"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x5c6370"

[colors.normal]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"
